version: "3.7"
services:
  my_service:
    container_name: my_service
    build: ./back_end
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "9000:9000"
    links:
      - my_service_db
    environment:
      - dev=1
      - NODE_DEV= product
      - db_service_name=my_service_db
      - db_name=learning
      - db_retry_time=3000
  my_service_db:
    container_name: my_service_db
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
